services:
  postgres_db_dagster:
    image: postgres:latest
    container_name: postgres_db_dagster
    environment:
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD: dagster
      POSTGRES_DB: dagster
    ports:
      - "5532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dagster"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_db_operational_db:
    image: postgres:latest
    container_name: postgres_db_operational_db
    environment:
      POSTGRES_USER: operation_db
      POSTGRES_PASSWORD: operation_db
      POSTGRES_DB: operation_db
    ports:
      - "5533:5432"
    volumes:
      - postgres_data_operational_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U operation_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_db_report_db:
    image: postgres:latest
    container_name: postgres_db_report_db
    environment:
      POSTGRES_USER: report_db
      POSTGRES_PASSWORD: report_db
      POSTGRES_DB: report_db
    ports:
      - "5534:5432"
    volumes:
      - postgres_data_report_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U report_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_db_grafana_db:
    image: postgres:latest
    container_name: postgres_db_grafana_db
    environment:
      POSTGRES_USER: grafana_db
      POSTGRES_PASSWORD: grafana_db
      POSTGRES_DB: grafana_db
    ports:
      - "5535:5432"
    volumes:
      - postgres_db_grafana_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U report_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  dagster_ui:
    build:
      context: .
      dockerfile: Dockerfiles/Dagster/Dockerfile
    container_name: dagster_ui
    command: ["uv", "run", "dagster-webserver", "-h", "0.0.0.0", "-p", "3000"]
    ports:
      - "3001:3000"
    environment:
      DAGSTER_POSTGRES_HOST: postgres_db_dagster
      DAGSTER_POSTGRES_DB: dagster
      DAGSTER_POSTGRES_USER: dagster
      DAGSTER_POSTGRES_PASSWORD: dagster
      DAGSTER_HOME: /opt/dagster/dagster_home
      DAGSTER_POSTGRES_PORT: 5532
    volumes:
      - ./dagster_home:/opt/dagster/dagster_home
      - ./src:/app/src
    depends_on:
      postgres_db_dagster:
        condition: service_healthy
      postgres_db_operational_db:
        condition: service_healthy

  dagster_daemon:
    build:
      context: .
      dockerfile: Dockerfiles/Dagster/Dockerfile
    container_name: dagster_daemon
    command: ["uv", "run", "dagster-daemon", "run"]
    environment:
      DAGSTER_POSTGRES_HOST: postgres_db_dagster
      DAGSTER_POSTGRES_DB: dagster
      DAGSTER_POSTGRES_USER: dagster
      DAGSTER_POSTGRES_PASSWORD: dagster
      DAGSTER_HOME: /opt/dagster/dagster_home
      DAGSTER_POSTGRES_PORT: 5532
    volumes:
      - ./dagster_home:/opt/dagster/dagster_home
      - ./src:/app/src
    depends_on:
      postgres_db_dagster:
        condition: service_healthy
    network_mode: host

volumes:
  postgres_data:
  postgres_data_operational_db:
  postgres_data_report_db:
  postgres_db_grafana_db:
